version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  postgres:
    image: postgres:14.4
    restart: on-failure
    environment:
      POSTGRES_DB: "real_estate"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "estate_attempt"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.2
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ESTATE
    volumes:
      - ./redis_data:/data

  receiver:
    build:
      dockerfile: ./receiver/Dockerfile
      context: ./
    env_file:
      - receiver/.env
    restart: on-failure
    ports:
      - "8000:3000"
    depends_on:
      - redis

volumes:
  prometheus_data:
  postgres_data:
  redis_data:
    driver: local