version: "3.9"
services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "real_estate"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "estate_attempt"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: