version: "3.9"
services:
  postgres:
    image: postgres:14.4
    restart: on-failure
    environment:
      POSTGRES_DB: "real_estate"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "estate_attempt"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.2
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ESTATE
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
  redis_data:
    driver: local